=== luis-lorenzo-gomez-blanco/lmgsi-dtd/mensajes3.dtd
<!ELEMENT mensajes (mensaje)*>
<!ELEMENT mensaje (persona,texto+)>
<!ELEMENT persona (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ATTLIST mensaje fecha CDATA #REQUIRED
    hora CDATA #REQUIRED
    franja CDATA #REQUIRED>

=== luis-lorenzo-gomez-blanco/lmgsi-dtd/mensajes3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mensajes SYSTEM "mensajes3.dtd">
<mensajes>
  <mensaje fecha="2025-01-01" hora="18:00" franja="GMT+1">
    <persona>Roberto Pérez</persona>
    <texto>Hola, ¿qué tal?</texto>
    <texto>Hace tiempo que no hablamos, ¿qué te cuentas?</texto>
  </mensaje>
  <mensaje fecha="2025-01-01" hora="18:10" franja="GMT+1">
    <persona>Verónica García</persona>
    <texto>Vamos a salir a tomar algo, ¿te apuntas?</texto>
  </mensaje>
</mensajes>
